---
- hosts: all
  tasks:
    - name: creating multiple
      file:
        path: /opt/{{item}}
        state: directory
        owner: root
        group: naveen
        mode: 0724
      with_items:
      - num1
      - num2
