---
- hosts: all
  tasks:
   - name: creating a file with content
     copy:
       dest: /opt/test-content1.py
       content:
           num1=50
           num2=60
           num3=120
           sum=num3+num2+num1
           print("the sum of three valuse")
           print(sum)
